version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:

      - MONGODB_URI=mongodb://mongo:27017/ecommerce_recommendation
      depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
